services:
  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "6831:6831/udp" # Jaeger agent UDP
      - "6832:6832/udp" # Jaeger agent UDP
      - "5778:5778" # Config endpoint
      - "16686:16686" # Jaeger UI
      - "4317:4317" # OpenTelemetry gRPC
      - "4318:4318" # OpenTelemetry HTTP
      - "14250:14250" # Jaeger collector gRPC
      - "14268:14268" # Jaeger collector HTTP
      - "14269:14269" # Additional Jaeger endpoints
      - "9411:9411" # Zipkin compatibility

